# Generated by PortfolioOps
FROM python:3.10-slim
WORKDIR /app

# Install system dependencies if needed (e.g. for cv2)
RUN apt-get update && apt-get install -y --no-install-recommends     libgl1-mesa-glx     libglib2.0-0     && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Default to 8000, can be overridden
ENV PORT=80
EXPOSE 80

# Assumes app.py or main.py exists
CMD ["python", "bot_framework.py"]
